### ISSUE TITLE
Do we want to generate a Console message if we try to scale a point?

### ISSUE THREAD

**Issue by boredompwndu** [danbuis/BBDGamesLib#1]
https://github.com/danbuis/BBDGamesLib/blob/5070d0354bb3b66ca8f4d92588168adb1f9e2594/src/Geometry2d/BBDPoint.java#L21

I could see a scenario where we get sloppy and try to scale all BBDGeometry's and this might get called. Not a big deal for say a triangle, but for a 100-gon this could get resource intensive and we should make an attempt to avoid it where possible by at least calling attention to it in testing

**Comment by danbuis** [comment]
How about an exception?

**Comment by boredompwndu** [comment]
without a proper understanding of how exceptions affect things, why not?
Like I don't want the program to crash out, I just want to call attention
to us being inefficient

**Comment by danbuis** [comment]
That's fair.  A quiet alert because while what they tried to do isn't illegal, it is certainly inefficient.

It makes sense not to "punish" them by crashing the program for making an accidental sub-optimal function call.
