### ISSUE TITLE
This breaks for parallel slopes

### ISSUE THREAD

**Issue by boredompwndu** [danbuis/BBDGamesLib#27]
https://github.com/danbuis/BBDGamesLib/blob/379d20bd9c749c79bd2294e55a45e2659f87b04d/src/Geometry2d/BBDSegment.java#L176-L178

**Comment by danbuis** [comment]
So it does.  Sounds like a good case for an exception.  I've found a few instances where that is a reasonable plan.  This will probably be the first implementation though.
