### ISSUE TITLE
Segment intersection - parallel segments are complicated

### ISSUE THREAD

**Issue by danbuis** [danbuis/BBDGamesLib#39]
Parallel segments either have 0, or infinite intersections.

If they are colinear and overlapping there are intersections.

Maybe it makes sense to add a function to Boolean intersection, and a function to math intersection points.
This came up due to polygons and their borders.

Until this is addressed polygons will continue to fail tests since we are unable to identify this as an overlap.

**Comment by danbuis** [comment]
Related to #27

**Comment by boredompwndu** [comment]
if lines are parallel, they should have the same X and/or Y intercept. No
idea how to present an infinite number of points in a collinear scenario
though

**Comment by danbuis** [comment]
Parallel lines are not guaranteed to have the same x or y intercepts.  Colinear ones will.

At the moment I'm planning a two tiered approach, kinda like battlecode.  First verify the lines to find the intersection aren't parallel, and then do the thing.

Parallel lines will throw an exception at runtime if they are parallel.  Ill be making a custom exception to be more useful instead of the semi cryptic divide by 0 exception.

**Comment by danbuis** [comment]
Added a block to catch these in the intersects() method that returns a boolean.  Basically adds a block for parallel and checks if any endpoints are on the other line.

Passes the related test in polygons now, so I'm satisfied.

Added some documentation to the comments on BBDSegment.intersects() and BBDSegment.interceptPoint() to explain expected use and and behavior regarding parallel lines.

Added a util function to determine parallel lines.
